config/routes.rb
Verbza::Application.routes.draw do
  root :to => "cards#new"

  devise_for :users do
    match 'users/sign_out' => 'devise/sessions#destroy' # So Devise plays nice with jQuery mobile
  end

  resources :decks do
    resources :cards
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  has_many :card_decks
  has_many :decks, :through => :card_decks

  attr_accessible :decks, :foreign_word, :native_word, :user_id, :image_file_name, :image, :image_url, :user

  has_attached_file :image,
      :styles => {
      :medium => "300x300>",
      :thumb => "100x100>" },
      :storage => :s3,
      :s3_credentials => {
        :bucket => ENV['AWS_BUCKET'],
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_KEY']
        },
      :path => "/:style/:id/:filename"


  validates :native_word,  :presence => true, :if => :foreign_word?
  validates :foreign_word, :presence => true, :if => :native_word?

  def foreign_word?
    :foreign_word == nil
  end

  def native_word?
    :native_word == nil
  end

  def next_card(deck)
    return false if deck.nil?
    deck.cards.where("cards.id > ?", id).first
  end

  def previous_card(deck)
    return false if deck.nil?
    deck.cards.where("cards.id < ?", id).last
  end


end

app/models/card_deck.rb
class CardDeck < ActiveRecord::Base
  self.table_name = "cards_decks"
  attr_accessible :card_id
  belongs_to :deck
  belongs_to :card

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user

  has_many :card_decks
  has_many :cards, :through => :card_decks

  attr_accessible :name, :user, :cards

  validates :name,
    presence: true

  def num_cards_in_deck
    self.cards.count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :default_deck
  has_many :decks
  has_many :cards
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :cards


  # attr_accessible :title, :body




  private

  def default_deck
    self.decks.create(:name => "All cards")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  private

  # def current_user
  #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #   end
  #   helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  respond_to :json, :html

  def index
    @deck = Deck.find(params[:deck_id])

    respond_to do |format|
      format.html
      format.json { respond_with @deck.cards }
    end
    # respond_with @deck.cards
    #render :json => @deck.cards
  end

  def new
    @card = Card.new
    @decks = current_user.decks[1..-1]
  end

  def create
    @deck = current_user.decks.find(params[:deck_id])
    @card = @deck.cards.build(params[:card])
    @card.user = current_user

    if params[:deck_ids].nil?
      @card.decks << current_user.decks.first
    else
      params[:deck_ids] << @deck.id
      @card.decks << Deck.find(params[:deck_ids])
    end

    if @card.save
      redirect_to deck_card_path(@deck, @card)
    else
      render 'new'
    end

    @card.image_url = @card.image.url(:medium)
    @card.save
  end

  def show
    @card = Card.find(params[:id])
    @deck = Deck.find(params[:deck_id])
  end

  def edit
    @card = Card.find(params[:id])
    @decks = current_user.decks[1..-1]
  end

  def update
    @card = Card.find(params[:id])
    @deck = current_user.decks.find(params[:deck_id])

    unless params[:deck_ids].nil?
      @card.decks << Deck.find(params[:deck_ids])
    end

    if @card.update_attributes(params[:card])
      redirect_to deck_card_path(params[:deck_id], @card)
    else
      render 'edit'
    end
  end

  def destroy
    @deck = Deck.find(params[:deck_id])
    @card = @deck.cards.find(params[:id])
    @deck.cards.delete(@card)

    redirect_to deck_cards_path(@deck)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :validate_user
  before_filter :find_deck, :only => [:show, :edit, :update, :destroy]

  def index
    @decks = current_user.decks
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = current_user.decks.new # pass user's id
  end

  def edit
  end

  def create
    @deck = current_user.decks.build(params[:deck])

    if @deck.save
      redirect_to decks_path
    else
      render 'new'
    end
  end

  def update
    if @deck.update_attributes(params[:deck])
      redirect_to deck_cards_path(@deck)
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy

    redirect_to decks_url
  end

  private

  def find_deck
    @deck = current_user.decks.find(params[:id])
  end

  def validate_user
    redirect_to root_url unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @card = Card.new
    @decks = current_user.decks
    #@decks = Deck.all
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

  before_filter :authenticate_user!

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
   :user
  end

  def resource
   @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/cards/_add_to_decks.html.erb
<div data-role="fieldcontain">
   <% @decks.each do |deck|%>
   <fieldset data-role="controlgroup">
     <%= f.check_box :deck_id, deck.id, @card.decks.include?(deck) %>
     <%= f.label deck.name %>
   </fieldset>
  <% end %>
  </div>
  
   <% @decks.each do |deck|%>
     <%= f.label deck.name %>
     <%= f.text_field %>
  <% end %>

app/views/cards/_form.html.erb
<%= form_for [current_user.decks.first, @card], :html => { :multipart => true, "data-ajax" => "false" } do |f| %>
 <div data-role="fieldcontain">
   <%= f.text_field :foreign_word, :placeholder => "Foreign Word" %>
 </div>
 <div data-role="fieldcontain">
   <%= f.text_field :native_word, :placeholder => "Native Word" %>
 </div>
 <% if @card.image_file_name %>
   <%= image_tag (@card.image.url(:medium)), :class => "image_on_edit_page" %>
   <div class="change_picture_button">
     <%= button_tag "Change picture", :type => "button", :id => "change_picture_button" %>
   </div>
   <div class="image_upload_1" data-role="fieldcontain">
     <%= f.label :image, "Upload an image: "%>
     <%= f.file_field :image %>
   </div>
 <% else %>
  <div class="image_upload" data-role="fieldcontain">
    <%= f.label :image, "Upload an image: " %>
    <%= f.file_field :image %>
  </div>
  <% end %>

  <div data-role="fieldcontain">
    <% @decks.each do |deck| %>


    <div class="checkbox_tag_custom" name="checkbox-<%=deck.id%>" >
        <%= check_box_tag "deck_ids[]", deck.id, false, {:id => "checkbox-#{deck.id}"}%>
    </div>
        <%= label_tag "checkbox-#{deck.id}", deck.name %>
      </fieldset>

     <% end %>
   <!-- LIST ALL DECKS WITH CHECKBOXES NEXT TO THEM -->
 </div>

 <%= f.submit %>
<% end %>

<script type="text/javascript">

$("#change_picture_button").on("click", function(event) {
  event.preventDefault();
   $(".image_on_edit_page").hide();
     $(".change_picture_button").hide();
     $(".image_upload_1").css("display", "block");
});
</script>

app/views/cards/edit.html.erb
<h2>Edit card</h2>
<%= render "form" %>

app/views/cards/index.html.erb
<h2><%= @deck.name %></h2>


<p data-role="button" data-inline="true" class="deck_button" data-mini="true"><%= link_to "Quiz", deck_path(@deck) %></p>
<p data-role="button" data-inline="true" class="deck_button" data-mini="true"><%= link_to "Edit", edit_deck_path(@deck) %></p>
<p data-role="button" data-inline="true" class="deck_button" data-mini="true"><%= link_to "Delete", deck_path(@deck), :method => :delete, :data => { :confirm => "Are you sure?" } %></p>


<div>
  <ul data-role="listview">
    <% @deck.cards.sort.each do |card| %>

    <li class="list_bar">
      <%= link_to "#{card.native_word} - #{card.foreign_word}", deck_card_path(@deck, card) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/cards/new.html.erb
<h2>new card</h2>


<%= render "form" %>

app/views/cards/new2.html.erb
<script type="text/javascript" charset="utf-8">
 var pictureSource; // picture source
 var destinationType; // sets the format of returned value

 // Wait for Cordova to connect with the device
 alert('got here');
 document.addEventListener("deviceready",onDeviceReady,false);

 // Cordova is ready to be used!
 function onDeviceReady() {
  alert ('got here 2');
  alert(navigator.camera);
 pictureSource=navigator.camera.PictureSourceType;
 destinationType=navigator.camera.DestinationType;
 }

 // Take picture using device camera and retrieve image as base64-encoded string
 function capturePhoto() {
 navigator.camera.getPicture(onPhotoDataSuccess, onFail, { quality: 50, allowEdit : true,
 destinationType: destinationType.DATA_URL });
 }

 // Called if something bad happens.
 function onFail(message) {
 alert('Failed because: ' + message);
 }

 function onPhotoDataSuccess(imageData) {
 // Uncomment to view the base64 encoded image data
 // console.log(imageData);

 // Unhide image elements
 largeImage.style.display = 'block';

 // Show the captured photo
 // The inline CSS rules are used to resize the image
 largeImage.src = "data:image/jpeg;base64," + imageData;
 }

 // Called when a photo is successfully retrieved
 function onPhotoURISuccess(imageURI) {
 // Uncomment to view the image file URI
 console.log(imageURI);

 // Get image handle
 var largeImage = document.getElementById('largeImage');

 // Unhide image elements
 largeImage.style.display = 'block';
 // Show the captured photo
 // The inline CSS rules are used to resize the image
 largeImage.src = imageURI;
 }
 </script>


<h2>New Card</h2>


<%= render "form" %>


<div data-role="content">
 <button data-theme="d" onclick="capturePhoto();">Capture Photo</button> <br>
 File Upload: <input type="file" name="jeffreytest"/>
 <img style="display:none;width:100%;" id="largeImage" src="" /> <br>
</div>

app/views/cards/show.html.erb
<div id="single_card_body">
  <div id="words">
    <h2 class="native_word_show_page"><%= @card.native_word %></h2>
    <p class="foreign_word_show_page"><%= @card.foreign_word%></p>
  </div>

<div id="img_in_show_card">
  <% if @card.image_file_name %>
    <%= image_tag @card.image.url(:medium) %>
  <% end %>

  <div id="card_edit_button">
    <p data-role="button" data-inline="true" data-mini="true"><%= link_to "Edit", edit_deck_card_path(@card.decks.first, @card) %></p>
    <p id="card_delete_button" data-role="button" data-inline="true" data-mini="true"><%= link_to "Delete", deck_card_path(@deck, @card), :method => :delete, :data => { :confirm => "Are you sure?" } %></p>
  </div>

<%  if @card.previous_card(@deck) %>
  <p data-role="button" data-inline="true" data-mini="true">
    <%= link_to "< Previous", deck_card_path(@deck.id , @card.previous_card(@deck)) %>
  </p>
<% end %>
  <p data-role="button" data-inline="true" data-mini="true">
    <%= link_to "New Card", new_deck_card_path(@card.decks.first) %>
  </p>
<%  if @card.next_card(@deck) %>
  <p data-role="button" data-inline="true" data-mini="true">
    <%= link_to "Next >", deck_card_path(@deck.id, @card.next_card(@deck)) %>
  </p>
<% end %>
</div>

app/views/decks/_form.html.erb
<%= form_for @deck do |f| %>
<div data-role="fieldcontain">
  <%= f.text_field :name, :placeholder => "Deckname" %>
</div>
  <%= f.submit %>

<% end %>

app/views/decks/edit.html.erb
<h2>Edit Deck</h2>
<%= render 'form' %>

app/views/decks/index.html.erb
<h2>All Decks - <%= current_user.email %></h2>


<div>
  <ul data-role="listview">
    <% @decks.each do |deck| %>
    <li class="list_bar">
    	<span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%="#{deck.num_cards_in_deck}"%></span>
      <%= link_to "#{deck.name} (#{deck.num_cards_in_deck})", deck_cards_path(deck) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/decks/new.html.erb
<h2>New Deck</h2>

<%= render "form" %>

app/views/decks/show.html.erb
<h2><%= @deck.name%> - Quiz</h2>

<div id="container_rectangle">
  <div id="picture_display"></div>
  <div id="card_rectangle">
    <div id="card_text">
      <a href="#"><p id="word_display">Start game</p></a>
    </div>
    <script type="text/javascript">deck = new Deck('<%= deck_cards_path @deck %>')</script>

  </div>
</div>
<!-- <div id="">

</div> -->

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render "cards/form" %>
<% else %>
  <%= render "devise/sessions/form", :controller => "devise/sessions"  %>
<% end %>

app/views/layouts/_header.html.erb
<!-- data-icon="grid" -->
<h1><p id="txtSpan"><%= link_to "verbza", root_url %></p></h1>
<ul id="menu-left" data-role="menu" >
  <li>
    <span data-role="button" data-icon="grid" data-iconpos="notext" ></span>
    <ul data-role="listview" data-inset="true">
      <%= render "layouts/nav_links" %>
    </ul>
  </li>
</ul>

<ul id="menu-right" data-role="menu" >
  <li>
    <span data-role="button" data-icon="gear" data-iconpos="notext"></span>
    <ul data-role="listview" data-inset="true">
      <%= render "layouts/setup_links" %>
    </ul>
  </li>
</ul>

app/views/layouts/_nav_links.html.erb
<% if user_signed_in? %>
  <li data-icon="false"><%= link_to "All Decks", decks_path %></li>
  <li data-icon="false"><%= link_to "All Cards", deck_cards_path(current_user.decks.first) %></li>
  <li data-icon="false"><%= link_to "New Deck", new_deck_path %></li>
  <li data-icon="false"><%= link_to "New Card", new_deck_card_path(current_user.decks.first) %></li>
<% end %>

app/views/layouts/_search.html.erb
<div class="search_input">
  <input type="search" name="search-mini" id="search-mini" value="" data-mini="true" />
</div>

app/views/layouts/_setup_links.html.erb
<% if user_signed_in? %>
  <li data-icon="false"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <li data-icon="false"><%= link_to "Edit profile", edit_user_registration_path %></li>
<% else %>
  <%= render "devise/shared/links" %>
<% end %>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->

<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- <link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'> -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'> -->
    <link href='http://fonts.googleapis.com/css?family=Racing+Sans+One' rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title><%= content_for?(:title) ? yield(:title) : "Verbza" %></title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim'%>


    <%= stylesheet_link_tag "application", :media => "all" %>

<!-- Loads faster at the end of the document? -->
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <%#= image_tag("background-large.jpg", class: "background_image") %>

    <div id="home" class="wrapper" data-role="page", data-theme="a">

      <div id="content" data-role="content">
        <%= yield %>
        <!-- # <%= debug params %> -->

      </div>

      <footer data-role="footer" data-position="fixed">
        <p>&copy; <span>verbza</span>, 2012</p>
      </footer>
       <header id="header" data-role="header">
          <%= render "layouts/header"%>
        </header>
    </div> <!-- /container -->

  </body>
</html>